### ISSUE TITLE
Add click listener to icon

### ISSUE THREAD

**Issue by code4jhon** [vuikit/vuikit#109]
```
<template>
<div>
  <div><vk-icons-cog v-on:click.native="onClick"></vk-icons-cog ></div> // doesn't work
  <test-cmp v-on:click="onClick"></test-cmp> // works
</div>
</template>
```

Shouldn't this work ?

Here is the SO I posted https://stackoverflow.com/questions/51200811/vue-onclick-doesnt-work-on-vuikit-icon 

(I created the tag vuikit so any questions related to the library can be tagged with it :) )

**Comment by miljan-aleksic** [comment]
The native modifier is used on more complex components, it is unnecessary for the icons. However your code would not work even without the native modifer and that will be fixed in next revisions.

Meantime you can wrap the icons with `vk-icon` or a simple `span` and apply the listeners to them, as suggested in StackOverflow.

Take in consideration that `vk-icons-cog` would render the raw icon, while `vk-icon icon="cog"` would render the icon wrapped with `span class="uk-icon"`, which is necessary for UIkit styling.
