### ISSUE TITLE
Dropdown works only with vuikit.css

### ISSUE THREAD

**Issue by dspangenberg** [vuikit/vuikit#30]
Hi,

please mention that some components need extra styling. For example the Dropdown displays only with vuikit.css. The styles provided by uikit aren't enough.

Regards, 
Danny

**Comment by miljan-aleksic** [comment]
Hi Danny,

there are no Vuikit specific styles for Dropdown. Make sure your UIkit theme is importing the uikit/dropdown.less styles.

**Comment by dspangenberg** [comment]
Hmm, strange. Even If I explicit import the dropdown.scss or use https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.1/css/uikit.css my dropdown doesn't appear. It works only with your vuikit.css. 

If I replace static/css/vuikit.css with https://cdnjs.cloudflare.com/ajax/libs/uikit/2.27.1/css/uikit.gradient.css in the index.ejs of your documentation the dropdown doesn't work too.

**Comment by miljan-aleksic** [comment]
I think I know what is about. Will confirm and get back with some feedback.

**Comment by miljan-aleksic** [comment]
Please build Vuikit from dev repo and try again, it should work now. If able, try the Modal display as well.

**Comment by dspangenberg** [comment]
Unfortunately it doesn't work neither im my own project nor with the the standard uikit.css in the documentation.

**Comment by miljan-aleksic** [comment]
Just tried it with latest UIkit default CSS and is working fine. Probably you are still loading the npm copy. You need to build Vuikit manually, delete the installed folder from your project node_modules and install from local folder (`npm i /mylocal/vuikit/repo`).

Otherwise, wait for the official release and update as usual.

**Comment by dspangenberg** [comment]
I'm sorry, that was my mistake. You're right, dropdown works now. But modals will not appear without vuikit.css.

**Comment by miljan-aleksic** [comment]
@dspangenberg, I have reconsidered the fix. As the issue is related about Vue/UIkit transitions differences, instead of applying workarounds in the JS code it's much more powerful to do so in the theme.

I have updated the README about, besides adding custom transitions it is necessary to reset the UIkit ones, as they are hardcoded. I hope UIkit 3 will have that fixed.

**Comment by dspangenberg** [comment]
Thats fine. Thanks for your rapid response!

**Comment by miljan-aleksic** [comment]
Just to clarify that the above workarounds are no longer necessary with Vuikit 0.8 and above.
