### ISSUE TITLE
What version of UIKit is supported?

### ISSUE THREAD

**Issue by muhajirframe** [vuikit/vuikit#68]

**Comment by miljan-aleksic** [comment]
UIkit 2. UIkit 3 based version is currently in development.

**Comment by muhajirframe** [comment]
Thanks, I really appreciate your works :)

**Comment by gustojs** [comment]
Just wanted to thank you for the hard work in `next` branch and leave a small notice that there are people interested in what's going on there. :)

**Comment by miljan-aleksic** [comment]
Thank you @gustojs :)

Vuikit next is being developed in parallel with a big Vue based project which is a great opportunity to create a useful library. But it is a one-man task and is taking a considerable amount of time, especially when there is a lot of refactoring going on.

I am determined to make Vuikit a solid UI solution and I am grateful to see interest in the next version.

**Comment by gustojs** [comment]
Just wondering. Are there some Uikit 3 Javascript features that you already know you're not planning to support? Such as `sortable`?

**Comment by miljan-aleksic** [comment]
There are no features I upfront discard, just at the moment, I am only porting features that are required by this Vue project. As the project is evolving more edge features are required, such as animations or components not part of UIkit.

For example, I am currently working on vk-tree that will render a data tree and allow nesting items, reordering, selecting, etc. UIkit ordering doesn't solve it entirely, thus was discarded temporary, because I do think it might be required in some future.

The ones I am not sure is about Slideshow and of a kind and I guess it depends on how well UIkit has worked out its abstraction. If its good, we could reuse their helpers and avoid reinventing the wheel.

BTW, the current Vuikit next state is quite stable. There is no documentation, for now, but if willing to play around just add `@vuikit/vuikit` as a dependency instead.

**Comment by gustojs** [comment]
Yeah reusing their own code and creating just a wrapper around it is a perfectly fine solution for more complex components.

I'm playing with `next` branch now, sadly it doesn't work with SSR due to relying on `document` without a check. If I make it work fine, I'll share the solution or make a PR.

**Comment by miljan-aleksic** [comment]
I have no experience with SSR but I do believe Vuikit should support it. Please do so :)

**Comment by gustojs** [comment]
Just wondering, you don't get
```
    ...rollupConfig,
    ^^^
SyntaxError: Unexpected token ...
```
during `build:dist`?

I get it even on node version 8.9.1, though 8.3 should support object spread operator.

**Comment by miljan-aleksic** [comment]
I don't and I have node 8.5, but there is no need to force it, I have updated the build.

BTW, lest open new tickets for any further issues.

**Comment by gustojs** [comment]
Thanks a lot, will do.
